version: '3.3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - .:/app
    entrypoint: ./entrypoint.sh bundle exec rails s -b 0.0.0.0
    environment:
      - HOST=db
      - USERNAME=postgres
      - PASSWORD=password
      - REDIS_URL=redis://redis:6379/0
  sidekiq:
    build:  
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    environment:
      - HOST=db
      - USERNAME=postgres
      - PASSWORD=password
      - REDIS_URL=redis://redis:6379/0
    command: bundle exec sidekiq

  redis:
    image: redis

volumes:
  db_data:
